# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.
#! set for Ropón-Palacios G. 
#! date 17:35 , Wed 9 Nov, 2022. 

package ifneeded autoionize 1.5 [list source [file join $dir FEMWgen_v1.0b.tcl]]
#package ifneeded autoionizegui 1.5 [list source [file join $dir autoionizegui.tcl]]
